name: compitax
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  platform_device_id: ^1.0.1
  flutter_splash_screen: ^1.0.0+6
  flutter_splash: ^1.0.1
  flutter_animated_splash: ^0.0.10
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.1
  awesome_dialog: ^2.2.1
  another_flushbar: ^1.10.29

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    # Logos
    - assets/imgs/app_logos/logo.png
    - assets/imgs/app_logos/logo1.png
    - assets/imgs/app_logos/logo2.png
    - assets/imgs/app_logos/splash_bg.png
    - assets/imgs/app_logos/phone_bg.png

    # Social Marks
    - assets/imgs/social_logos/google-logo.png
    - assets/imgs/social_logos/facebook-logo.png
    - assets/imgs/social_logos/truecaller-logo.png

    # State Stamp
    - assets/imgs/stamp/_active.png
    - assets/imgs/stamp/_completed.png
    - assets/imgs/stamp/_cancelled.png
    - assets/imgs/stamp/1-active.png
    - assets/imgs/stamp/1-completed.png
    - assets/imgs/stamp/1-cancelled.png

    #
    - assets/imgs/extra/_border_s.png
    - assets/imgs/extra/_border_l.png
    - assets/imgs/extra/_dashed_s.png
    - assets/imgs/extra/_dashed_l.png
    - assets/imgs/extra/_from.png
    - assets/imgs/extra/_to.png
    - assets/imgs/extra/check.png
    - assets/imgs/extra/from_to.png
    - assets/imgs/extra/paidByOlaMoney.png

    # background
    - assets/imgs/bg/img1.jpg
    - assets/imgs/bg/img2.jpg
    - assets/imgs/bg/img3.jpg
    - assets/imgs/bg/img4.jpg
    # - assets/imgs/bg/img5.jpg
    # - assets/imgs/bg/img6.jpg
    - assets/imgs/bg/img7.jpg
    - assets/imgs/bg/img8.jpg
    - assets/imgs/bg/img9.jpg
    - assets/imgs/bg/img10.jpg
    - assets/imgs/bg/img11.jpg
    - assets/imgs/bg/img12.jpg
    - assets/imgs/bg/img13.jpg
    - assets/imgs/bg/img101.png
    - assets/imgs/bg/img102.jpg
    - assets/imgs/bg/img103.png
    - assets/imgs/bg/img104.jpg
    - assets/imgs/bg/img105.jpg

    # others
    - assets/imgs/bg1.jpg
    - assets/imgs/user1.jpg
    - assets/imgs/user2.jpg

    # service cimpany logos
    - assets/providers/bolt/bolt1.png
    - assets/providers/bolt/bolt2.png
    - assets/providers/bolt/bolt3.png
    - assets/providers/bolt/bolt4.png
    - assets/providers/uber/uber2.png
    - assets/providers/uber/uber3.png
    - assets/providers/uber/uber4.png
    - assets/providers/gett/gett1.png
    - assets/providers/gett/gett3.png
    - assets/providers/gett/gett4.png

    - assets/providers/grab1.png
    - assets/providers/grab3.png
    - assets/providers/smrt1.png
    - assets/providers/smrt2.png

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600

    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
